name: Publish to NPM
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Copy README.md to the lib
        run: cp README.md ./packages/decision-tree-maker-lib/README.md
      - name: Install dependencies and build 🔧
        run: cd ./packages/decision-tree-maker-lib && yarn && yarn build
      - name: Publish package on NPM 📦
        run: cd ./packages/decision-tree-maker-lib && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
